server:
  port: 8080
  servlet:
    context-path: /api/v1

application:
  age-constraint: 18

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      pool-name: Hikari
      auto-commit: false
  sql:
    init:
      mode: always
  jpa:
    open-in-view: true
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
